# Generated by Django 4.1.2 on 2022-12-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_marksheet',
            name='data_of_birth',
            field=models.CharField(max_length=10),
        ),
    ]
